route:
    receiver: 'slack'

receivers:
  - name: slack
    slack_configs:
    - channel: '#alerts'
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      api_url: 'https://hooks.slack.com/services/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'
      send_resolved: true
      title: '{{ template "custom_title" . }}'
      text: '{{ template "custom_slack_message" . }}'

templates:
- notifications.tmpl